### ISSUE TITLE
[FEATURE]: CSS-variable for font-family

### ISSUE THREAD

**Issue by projct1** [jackdomleo7/Cooltipz.css#65]
Now is hardcoded. Have to use crutch:
```css
[aria-label][data-cooltipz-dir]::after, [aria-label][class*=cooltipz]::after {
  font-family: $font-family-base;
}
```
